name: Selenium Test

on:
  push:
    branches:
      - master

jobs:
  selenium:
    runs-on: ubuntu-latest #roda em  uma  maquina virtual   Ubuntu-latest

    steps:
      - name: Checkout code # o código fonte é baixado com o uso da ação "checkout" do GitHub.
        uses: actions/checkout@v2

      - name: Set up Node.js #  configuração da versão do Node.js que será usada na execução do teste.
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm install

      - name: Start Selenium
        run: |
          export DISPLAY=:99
          /usr/bin/Xvfb :99 -screen 0 1024x768x16 +extension RANDR &
          sleep 3
          chromedriver --url-base=/wd/hub &
      - name: Run Selenium tests
        run: npm run test